--------------------------------------------------------
-- AEROPUERTO AURORA - DATA DE PRUEBA SEGURA
-- Ejecutar despues del script principal.
-- Limpia primero la data de prueba parcial y vuelve a insertar con IDs fijos.
--------------------------------------------------------
SET DEFINE OFF;
ALTER SESSION SET CURRENT_SCHEMA = AEROPUERTO_AURORA;

--------------------------------------------------------
-- LIMPIEZA EN ORDEN HIJO -> PADRE
--------------------------------------------------------
DELETE FROM "AEROPUERTO_AURORA"."AER_AUDITORIA";
DELETE FROM "AEROPUERTO_AURORA"."AER_OBJETOPERDIDO";
DELETE FROM "AEROPUERTO_AURORA"."AER_ARRESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_INCIDENTE";
DELETE FROM "AEROPUERTO_AURORA"."AER_REPUESTOUTILIZADO";
DELETE FROM "AEROPUERTO_AURORA"."AER_MANTENIMIENTOAVION";
DELETE FROM "AEROPUERTO_AURORA"."AER_DETALLEORDENCOMPRA";
DELETE FROM "AEROPUERTO_AURORA"."AER_ORDENCOMPRAREPUESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_MOVIMIENTOREPUESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_REPUESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PROVEEDOR";
DELETE FROM "AEROPUERTO_AURORA"."AER_CATEGORIAREPUESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_ASIGNACIONHANGAR";
DELETE FROM "AEROPUERTO_AURORA"."AER_HANGAR";
DELETE FROM "AEROPUERTO_AURORA"."AER_CONTROL_SEGURIDAD";
DELETE FROM "AEROPUERTO_AURORA"."AER_CONTROL_MIGRATORIO";
DELETE FROM "AEROPUERTO_AURORA"."AER_MOVIMIENTO_EQUIPAJE";
DELETE FROM "AEROPUERTO_AURORA"."AER_EQUIPAJE";
DELETE FROM "AEROPUERTO_AURORA"."AER_TARJETA_EMBARQUE";
DELETE FROM "AEROPUERTO_AURORA"."AER_CHECKIN";
DELETE FROM "AEROPUERTO_AURORA"."AER_USOPROMOCION";
DELETE FROM "AEROPUERTO_AURORA"."AER_TRANSACCIONPAGO";
DELETE FROM "AEROPUERTO_AURORA"."AER_DETALLEVENTABOLETO";
DELETE FROM "AEROPUERTO_AURORA"."AER_VENTABOLETO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PUNTOVENTA";
DELETE FROM "AEROPUERTO_AURORA"."AER_CLICKDESTINO";
DELETE FROM "AEROPUERTO_AURORA"."AER_BUSQUEDAVUELO";
DELETE FROM "AEROPUERTO_AURORA"."AER_ITEMCARRITO";
DELETE FROM "AEROPUERTO_AURORA"."AER_CARRITOCOMPRA";
DELETE FROM "AEROPUERTO_AURORA"."AER_ASIGNACION_ASIENTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_RESERVA";
DELETE FROM "AEROPUERTO_AURORA"."AER_ASIGNACION_PUERTA";
DELETE FROM "AEROPUERTO_AURORA"."AER_TRIPULACION";
DELETE FROM "AEROPUERTO_AURORA"."AER_VUELO";
DELETE FROM "AEROPUERTO_AURORA"."AER_DIASVUELO";
DELETE FROM "AEROPUERTO_AURORA"."AER_ESCALATECNICA";
DELETE FROM "AEROPUERTO_AURORA"."AER_PROGRAMAVUELO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PREFERENCIACLIENTE";
DELETE FROM "AEROPUERTO_AURORA"."AER_SESIONUSUARIO";
DELETE FROM "AEROPUERTO_AURORA"."AER_USUARIO_LOGIN";
DELETE FROM "AEROPUERTO_AURORA"."AER_PASAJERO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PLANILLA";
DELETE FROM "AEROPUERTO_AURORA"."AER_ASISTENCIA";
DELETE FROM "AEROPUERTO_AURORA"."AER_LICENCIAEMPLEADO";
DELETE FROM "AEROPUERTO_AURORA"."AER_EMPLEADO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PUESTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_DEPARTAMENTO";
DELETE FROM "AEROPUERTO_AURORA"."AER_PROMOCION";
DELETE FROM "AEROPUERTO_AURORA"."AER_METODOPAGO";
DELETE FROM "AEROPUERTO_AURORA"."AER_ASIENTO_AVION";
DELETE FROM "AEROPUERTO_AURORA"."AER_AVION";
DELETE FROM "AEROPUERTO_AURORA"."AER_MODELOAVION";
DELETE FROM "AEROPUERTO_AURORA"."AER_AEROLINEA";
DELETE FROM "AEROPUERTO_AURORA"."AER_PUERTA_EMBARQUE";
DELETE FROM "AEROPUERTO_AURORA"."AER_TERMINAL";
DELETE FROM "AEROPUERTO_AURORA"."AER_AEROPUERTO";
COMMIT;

--------------------------------------------------------
-- CATALOGOS
--------------------------------------------------------
INSERT INTO "AEROPUERTO_AURORA"."AER_AEROPUERTO" ("AER_ID","AER_CODIGO_AEROPUERTO","AER_NOMBRE","AER_CIUDAD","AER_PAIS","AER_ZONA_HORARIA","AER_ESTADO","AER_TIPO","AER_LATITUD","AER_LONGITUD","AER_CODIGO_IATA","AER_CODIGO_ICAO") VALUES (1,'GUA-AUR','Aeropuerto Internacional La Aurora','Ciudad de Guatemala','Guatemala','America/Guatemala','ACTIVO','internacional',14.5833,-90.5275,'GUA','MGGT');
INSERT INTO "AEROPUERTO_AURORA"."AER_AEROPUERTO" ("AER_ID","AER_CODIGO_AEROPUERTO","AER_NOMBRE","AER_CIUDAD","AER_PAIS","AER_ZONA_HORARIA","AER_ESTADO","AER_TIPO","AER_LATITUD","AER_LONGITUD","AER_CODIGO_IATA","AER_CODIGO_ICAO") VALUES (2,'SAL-MON','Aeropuerto Internacional de El Salvador','San Salvador','El Salvador','America/El_Salvador','ACTIVO','internacional',13.4409,-89.0557,'SAL','MSLP');
INSERT INTO "AEROPUERTO_AURORA"."AER_AEROPUERTO" ("AER_ID","AER_CODIGO_AEROPUERTO","AER_NOMBRE","AER_CIUDAD","AER_PAIS","AER_ZONA_HORARIA","AER_ESTADO","AER_TIPO","AER_LATITUD","AER_LONGITUD","AER_CODIGO_IATA","AER_CODIGO_ICAO") VALUES (3,'MEX-AICM','Aeropuerto Internacional Benito Juarez','Ciudad de Mexico','Mexico','America/Mexico_City','ACTIVO','internacional',19.4361,-99.0719,'MEX','MMMX');

INSERT INTO "AEROPUERTO_AURORA"."AER_TERMINAL" ("TER_ID_TERMINAL","TER_ID_AEROPUERTO","TER_NOMBRE","TER_TIPO","TER_CAPACIDAD_PASAJEROS","TER_ESTADO") VALUES (1,1,'Terminal Central','internacional',2500000,'ACTIVA');
INSERT INTO "AEROPUERTO_AURORA"."AER_TERMINAL" ("TER_ID_TERMINAL","TER_ID_AEROPUERTO","TER_NOMBRE","TER_TIPO","TER_CAPACIDAD_PASAJEROS","TER_ESTADO") VALUES (2,1,'Terminal Nacional','nacional',900000,'ACTIVA');

INSERT INTO "AEROPUERTO_AURORA"."AER_PUERTA_EMBARQUE" ("PUE_ID_PUERTA","PUE_ID_TERMINAL","PUE_CODIGO","PUE_ESTADO","PUE_TIPO") VALUES (1,1,'A1','DISPONIBLE','internacional');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUERTA_EMBARQUE" ("PUE_ID_PUERTA","PUE_ID_TERMINAL","PUE_CODIGO","PUE_ESTADO","PUE_TIPO") VALUES (2,1,'A2','DISPONIBLE','internacional');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUERTA_EMBARQUE" ("PUE_ID_PUERTA","PUE_ID_TERMINAL","PUE_CODIGO","PUE_ESTADO","PUE_TIPO") VALUES (3,2,'B1','DISPONIBLE','nacional');

INSERT INTO "AEROPUERTO_AURORA"."AER_AEROLINEA" ("ARL_ID","ARL_CODIGO_AEROLINEA","ARL_NOMBRE","ARL_PAIS_ORIGEN","ARL_CODIGO_IATA","ARL_CODIGO_ICAO","ARL_ESTADO","ARL_EMAIL") VALUES (1,'AV-GT','Avianca Guatemala','Guatemala','AV','AVA','ACTIVA','ops.gt@avianca.test');
INSERT INTO "AEROPUERTO_AURORA"."AER_AEROLINEA" ("ARL_ID","ARL_CODIGO_AEROLINEA","ARL_NOMBRE","ARL_PAIS_ORIGEN","ARL_CODIGO_IATA","ARL_CODIGO_ICAO","ARL_ESTADO","ARL_EMAIL") VALUES (2,'TA-GT','TAG Airlines','Guatemala','5U','TGU','ACTIVA','ops@tag.test');

INSERT INTO "AEROPUERTO_AURORA"."AER_MODELOAVION" ("MOD_ID_MODELO","MOD_NOMBRE_MODELO","MOD_FABRICANTE","MOD_CAPACIDAD_PASAJEROS","MOD_CAPACIDAD_CARGA","MOD_ALCANCE_KM","MOD_VELOCIDAD_CRUCERO","MOD_ANIO_INTRODUCCION","MOD_TIPO_MOTOR") VALUES (1,'Airbus A320neo','Airbus',180,19000,6300,829,2016,'Turbofan');
INSERT INTO "AEROPUERTO_AURORA"."AER_MODELOAVION" ("MOD_ID_MODELO","MOD_NOMBRE_MODELO","MOD_FABRICANTE","MOD_CAPACIDAD_PASAJEROS","MOD_CAPACIDAD_CARGA","MOD_ALCANCE_KM","MOD_VELOCIDAD_CRUCERO","MOD_ANIO_INTRODUCCION","MOD_TIPO_MOTOR") VALUES (2,'ATR 72-600','ATR',72,7500,1528,510,2010,'Turbohelice');

INSERT INTO "AEROPUERTO_AURORA"."AER_AVION" ("AVI_ID","AVI_MATRICULA","AVI_ID_MODELO","AVI_ID_AEROLINEA","AVI_ANIO_FABRICACION","AVI_ESTADO","AVI_ULTIMA_REVISION","AVI_PROXIMA_REVISION","AVI_HORAS_VUELO") VALUES (1,'TG-AVA1',1,1,2021,'ACTIVO',DATE '2026-02-15',DATE '2026-08-15',2140);
INSERT INTO "AEROPUERTO_AURORA"."AER_AVION" ("AVI_ID","AVI_MATRICULA","AVI_ID_MODELO","AVI_ID_AEROLINEA","AVI_ANIO_FABRICACION","AVI_ESTADO","AVI_ULTIMA_REVISION","AVI_PROXIMA_REVISION","AVI_HORAS_VUELO") VALUES (2,'TG-TAG2',2,2,2019,'ACTIVO',DATE '2026-03-10',DATE '2026-09-10',1875);

INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (1,1,'1A','primera','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (2,1,'12A','economica','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (3,1,'12B','economica','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (4,2,'2A','ejecutiva','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (5,2,'8A','economica','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIENTO_AVION" ("ASA_ID_ASIENTO","ASA_ID_AVION","ASA_CODIGO","ASA_CLASE","ASA_ESTADO") VALUES (6,2,'8B','economica','DISPONIBLE');

INSERT INTO "AEROPUERTO_AURORA"."AER_METODOPAGO" ("MET_ID_METODO_PAGO","MET_NOMBRE","MET_TIPO","MET_ESTADO","MET_COMISION_PORCENTAJE") VALUES (1,'Tarjeta Visa','tarjeta','ACTIVO',2.50);
INSERT INTO "AEROPUERTO_AURORA"."AER_METODOPAGO" ("MET_ID_METODO_PAGO","MET_NOMBRE","MET_TIPO","MET_ESTADO","MET_COMISION_PORCENTAJE") VALUES (2,'Efectivo mostrador','efectivo','ACTIVO',0);
INSERT INTO "AEROPUERTO_AURORA"."AER_METODOPAGO" ("MET_ID_METODO_PAGO","MET_NOMBRE","MET_TIPO","MET_ESTADO","MET_COMISION_PORCENTAJE") VALUES (3,'Billetera digital','digital','ACTIVO',1.25);

INSERT INTO "AEROPUERTO_AURORA"."AER_PROMOCION" ("PRO_ID_PROMOCION","PRO_CODIGO_PROMOCION","PRO_DESCRIPCION","PRO_TIPO_DESCUENTO","PRO_VALOR_DESCUENTO","PRO_FECHA_INICIO","PRO_FECHA_FIN","PRO_USOS_MAXIMOS","PRO_USOS_ACTUALES","PRO_ESTADO") VALUES (1,'AURORA10','Descuento de lanzamiento web','porcentaje',10,DATE '2026-04-01',DATE '2026-12-31',500,1,'ACTIVA');

--------------------------------------------------------
-- EMPLEADOS
--------------------------------------------------------
INSERT INTO "AEROPUERTO_AURORA"."AER_DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO","DEP_NOMBRE","DEP_DESCRIPCION","DEP_ID_AEROPUERTO","DEP_ESTADO") VALUES (1,'Operaciones','Control de operaciones aeroportuarias',1,'ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO","DEP_NOMBRE","DEP_DESCRIPCION","DEP_ID_AEROPUERTO","DEP_ESTADO") VALUES (2,'Seguridad','Controles y seguridad de pasajeros',1,'ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO","DEP_NOMBRE","DEP_DESCRIPCION","DEP_ID_AEROPUERTO","DEP_ESTADO") VALUES (3,'Mantenimiento','Mantenimiento de aeronaves',1,'ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO","DEP_NOMBRE","DEP_DESCRIPCION","DEP_ID_AEROPUERTO","DEP_ESTADO") VALUES (4,'Ventas','Venta de boletos',1,'ACTIVO');

INSERT INTO "AEROPUERTO_AURORA"."AER_PUESTO" ("PUE_ID_PUESTO","PUE_NOMBRE","PUE_ID_DEPARTAMENTO","PUE_DESCRIPCION","PUE_SALARIO_MINIMO","PUE_SALARIO_MAXIMO","PUE_REQUIERE_LICENCIA") VALUES (1,'Piloto',1,'Piloto comercial',18000,35000,'S');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUESTO" ("PUE_ID_PUESTO","PUE_NOMBRE","PUE_ID_DEPARTAMENTO","PUE_DESCRIPCION","PUE_SALARIO_MINIMO","PUE_SALARIO_MAXIMO","PUE_REQUIERE_LICENCIA") VALUES (2,'Copiloto',1,'Copiloto comercial',12000,24000,'S');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUESTO" ("PUE_ID_PUESTO","PUE_NOMBRE","PUE_ID_DEPARTAMENTO","PUE_DESCRIPCION","PUE_SALARIO_MINIMO","PUE_SALARIO_MAXIMO","PUE_REQUIERE_LICENCIA") VALUES (3,'Agente de seguridad',2,'Revision de pasajeros',4200,7000,'N');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUESTO" ("PUE_ID_PUESTO","PUE_NOMBRE","PUE_ID_DEPARTAMENTO","PUE_DESCRIPCION","PUE_SALARIO_MINIMO","PUE_SALARIO_MAXIMO","PUE_REQUIERE_LICENCIA") VALUES (4,'Tecnico aeronautico',3,'Mantenimiento preventivo',8500,16000,'S');
INSERT INTO "AEROPUERTO_AURORA"."AER_PUESTO" ("PUE_ID_PUESTO","PUE_NOMBRE","PUE_ID_DEPARTAMENTO","PUE_DESCRIPCION","PUE_SALARIO_MINIMO","PUE_SALARIO_MAXIMO","PUE_REQUIERE_LICENCIA") VALUES (5,'Vendedor mostrador',4,'Venta presencial',3800,6200,'N');

INSERT INTO "AEROPUERTO_AURORA"."AER_EMPLEADO" ("EMP_ID_EMPLEADO","EMP_NUMERO_EMPLEADO","EMP_PRIMER_NOMBRE","EMP_PRIMER_APELLIDO","EMP_FECHA_NACIMIENTO","EMP_DPI","EMP_NIT","EMP_TELEFONO","EMP_EMAIL","EMP_FECHA_CONTRATACION","EMP_ID_PUESTO","EMP_ID_DEPARTAMENTO","EMP_SALARIO_ACTUAL","EMP_TIPO_CONTRATO","EMP_ESTADO") VALUES (1,'EMP-001','Carlos','Mendez',DATE '1984-03-12','1000000000101','1234567-8','5550-1001','carlos.mendez@aurora.test',DATE '2015-02-01',1,1,28500,'indefinido','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_EMPLEADO" ("EMP_ID_EMPLEADO","EMP_NUMERO_EMPLEADO","EMP_PRIMER_NOMBRE","EMP_PRIMER_APELLIDO","EMP_FECHA_NACIMIENTO","EMP_DPI","EMP_NIT","EMP_TELEFONO","EMP_EMAIL","EMP_FECHA_CONTRATACION","EMP_ID_PUESTO","EMP_ID_DEPARTAMENTO","EMP_SALARIO_ACTUAL","EMP_TIPO_CONTRATO","EMP_ESTADO") VALUES (2,'EMP-002','Andrea','Castillo',DATE '1990-07-22','1000000000102','2234567-8','5550-1002','andrea.castillo@aurora.test',DATE '2018-04-15',2,1,17200,'indefinido','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_EMPLEADO" ("EMP_ID_EMPLEADO","EMP_NUMERO_EMPLEADO","EMP_PRIMER_NOMBRE","EMP_PRIMER_APELLIDO","EMP_FECHA_NACIMIENTO","EMP_DPI","EMP_NIT","EMP_TELEFONO","EMP_EMAIL","EMP_FECHA_CONTRATACION","EMP_ID_PUESTO","EMP_ID_DEPARTAMENTO","EMP_SALARIO_ACTUAL","EMP_TIPO_CONTRATO","EMP_ESTADO") VALUES (3,'EMP-003','Mario','Ramirez',DATE '1988-02-18','1000000000103','3234567-8','5550-1003','mario.ramirez@aurora.test',DATE '2019-09-10',3,2,5600,'indefinido','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_EMPLEADO" ("EMP_ID_EMPLEADO","EMP_NUMERO_EMPLEADO","EMP_PRIMER_NOMBRE","EMP_PRIMER_APELLIDO","EMP_FECHA_NACIMIENTO","EMP_DPI","EMP_NIT","EMP_TELEFONO","EMP_EMAIL","EMP_FECHA_CONTRATACION","EMP_ID_PUESTO","EMP_ID_DEPARTAMENTO","EMP_SALARIO_ACTUAL","EMP_TIPO_CONTRATO","EMP_ESTADO") VALUES (4,'EMP-004','Jorge','Alvarado',DATE '1986-12-08','1000000000104','4234567-8','5550-1004','jorge.alvarado@aurora.test',DATE '2017-11-03',4,3,12800,'indefinido','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_EMPLEADO" ("EMP_ID_EMPLEADO","EMP_NUMERO_EMPLEADO","EMP_PRIMER_NOMBRE","EMP_PRIMER_APELLIDO","EMP_FECHA_NACIMIENTO","EMP_DPI","EMP_NIT","EMP_TELEFONO","EMP_EMAIL","EMP_FECHA_CONTRATACION","EMP_ID_PUESTO","EMP_ID_DEPARTAMENTO","EMP_SALARIO_ACTUAL","EMP_TIPO_CONTRATO","EMP_ESTADO") VALUES (5,'EMP-005','Paola','Lopez',DATE '1997-05-14','1000000000105','5234567-8','5550-1005','paola.lopez@aurora.test',DATE '2022-03-25',5,4,4800,'indefinido','ACTIVO');

INSERT INTO "AEROPUERTO_AURORA"."AER_LICENCIAEMPLEADO" ("LIC_ID_LICENCIA","LIC_ID_EMPLEADO","LIC_TIPO_LICENCIA","LIC_NUMERO_LICENCIA","LIC_FECHA_EMISION","LIC_FECHA_VENCIMIENTO","LIC_AUTORIDAD_EMISORA","LIC_ESTADO") VALUES (1,1,'Piloto comercial','LIC-PIL-001',DATE '2023-01-10',DATE '2027-01-10','DGAC Guatemala','VIGENTE');
INSERT INTO "AEROPUERTO_AURORA"."AER_LICENCIAEMPLEADO" ("LIC_ID_LICENCIA","LIC_ID_EMPLEADO","LIC_TIPO_LICENCIA","LIC_NUMERO_LICENCIA","LIC_FECHA_EMISION","LIC_FECHA_VENCIMIENTO","LIC_AUTORIDAD_EMISORA","LIC_ESTADO") VALUES (2,2,'Copiloto comercial','LIC-COP-002',DATE '2023-04-12',DATE '2027-04-12','DGAC Guatemala','VIGENTE');
INSERT INTO "AEROPUERTO_AURORA"."AER_LICENCIAEMPLEADO" ("LIC_ID_LICENCIA","LIC_ID_EMPLEADO","LIC_TIPO_LICENCIA","LIC_NUMERO_LICENCIA","LIC_FECHA_EMISION","LIC_FECHA_VENCIMIENTO","LIC_AUTORIDAD_EMISORA","LIC_ESTADO") VALUES (3,4,'Tecnico aeronautico','LIC-MAN-004',DATE '2022-06-15',DATE '2026-06-15','DGAC Guatemala','VIGENTE');

INSERT INTO "AEROPUERTO_AURORA"."AER_PLANILLA" ("PLA_ID_PLANILLA","PLA_ID_EMPLEADO","PLA_PERIODO_INICIO","PLA_PERIODO_FIN","PLA_SALARIO_BASE","PLA_BONIFICACIONES","PLA_HORAS_EXTRA","PLA_DEDUCCIONES","PLA_SALARIO_NETO","PLA_FECHA_PAGO","PLA_ESTADO") VALUES (1,1,DATE '2026-04-01',DATE '2026-04-30',28500,500,0,1500,27500,DATE '2026-04-30','PAGADA');

--------------------------------------------------------
-- PASAJEROS, LOGIN Y VUELOS
--------------------------------------------------------
INSERT INTO "AEROPUERTO_AURORA"."AER_PASAJERO" ("PAS_ID_PASAJERO","PAS_NUMERO_DOCUMENTO","PAS_TIPO_DOCUMENTO","PAS_PRIMER_NOMBRE","PAS_SEGUNDO_NOMBRE","PAS_PRIMER_APELLIDO","PAS_SEGUNDO_APELLIDO","PAS_FECHA_NACIMIENTO","PAS_NACIONALIDAD","PAS_SEXO","PAS_TELEFONO","PAS_EMAIL") VALUES (1,'3000000000101','DPI','Luis','Fernando','Perez','Gomez',DATE '1998-01-15','Guatemalteca','M','5600-0001','luis.perez@mail.test');
INSERT INTO "AEROPUERTO_AURORA"."AER_PASAJERO" ("PAS_ID_PASAJERO","PAS_NUMERO_DOCUMENTO","PAS_TIPO_DOCUMENTO","PAS_PRIMER_NOMBRE","PAS_SEGUNDO_NOMBRE","PAS_PRIMER_APELLIDO","PAS_SEGUNDO_APELLIDO","PAS_FECHA_NACIMIENTO","PAS_NACIONALIDAD","PAS_SEXO","PAS_TELEFONO","PAS_EMAIL") VALUES (2,'3000000000102','DPI','Maria','Jose','Ruiz','Castro',DATE '1996-08-11','Guatemalteca','F','5600-0002','maria.ruiz@mail.test');
INSERT INTO "AEROPUERTO_AURORA"."AER_PASAJERO" ("PAS_ID_PASAJERO","PAS_NUMERO_DOCUMENTO","PAS_TIPO_DOCUMENTO","PAS_PRIMER_NOMBRE","PAS_SEGUNDO_NOMBRE","PAS_PRIMER_APELLIDO","PAS_SEGUNDO_APELLIDO","PAS_FECHA_NACIMIENTO","PAS_NACIONALIDAD","PAS_SEXO","PAS_TELEFONO","PAS_EMAIL") VALUES (3,'P-CR-9001','pasaporte','Daniel',NULL,'Soto','Vargas',DATE '1987-05-20','Costarricense','M','5600-0003','daniel.soto@mail.test');

INSERT INTO "AEROPUERTO_AURORA"."AER_USUARIO_LOGIN" ("USL_ID_USUARIO","USL_ID_PASAJERO","USL_USUARIO","USL_EMAIL","USL_CONTRASENA_HASH","USL_SAL","USL_ESTADO","USL_EMAIL_VERIFICADO","USL_INTENTOS_FALLIDOS") VALUES (1,1,'luis.perez','luis.perez@mail.test','$2a$10$demoHashLuis','salt-luis','ACTIVO','S',0);
INSERT INTO "AEROPUERTO_AURORA"."AER_USUARIO_LOGIN" ("USL_ID_USUARIO","USL_ID_PASAJERO","USL_USUARIO","USL_EMAIL","USL_CONTRASENA_HASH","USL_SAL","USL_ESTADO","USL_EMAIL_VERIFICADO","USL_INTENTOS_FALLIDOS") VALUES (2,2,'maria.ruiz','maria.ruiz@mail.test','$2a$10$demoHashMaria','salt-maria','ACTIVO','S',0);
INSERT INTO "AEROPUERTO_AURORA"."AER_USUARIO_LOGIN" ("USL_ID_USUARIO","USL_ID_PASAJERO","USL_USUARIO","USL_EMAIL","USL_CONTRASENA_HASH","USL_SAL","USL_ESTADO","USL_EMAIL_VERIFICADO","USL_INTENTOS_FALLIDOS") VALUES (3,3,'daniel.soto','daniel.soto@mail.test','$2a$10$demoHashDaniel','salt-daniel','ACTIVO','N',1);

INSERT INTO "AEROPUERTO_AURORA"."AER_SESIONUSUARIO" ("SES_ID_SESION","SES_SESION_ID","SES_ID_USUARIO","SES_ID_PASAJERO","SES_IP_ADDRESS","SES_NAVEGADOR","SES_SISTEMA_OPERATIVO","SES_DISPOSITIVO") VALUES (1,'SES-001-LUIS',1,1,'192.168.1.10','Chrome','Windows','Laptop');
INSERT INTO "AEROPUERTO_AURORA"."AER_PREFERENCIACLIENTE" ("PRF_ID_PREFERENCIA","PRF_ID_PASAJERO","PRF_TIPO_PREFERENCIA","PRF_VALOR_PREFERENCIA") VALUES (1,1,'asiento','ventana');

INSERT INTO "AEROPUERTO_AURORA"."AER_PROGRAMAVUELO" ("PRV_ID","PRV_NUMERO_VUELO","PRV_ID_AEROLINEA","PRV_ID_AEROPUERTO_ORIGEN","PRV_ID_AEROPUERTO_DESTINO","PRV_HORA_SALIDA_PROGRAMADA","PRV_HORA_LLEGADA_PROGRAMADA","PRV_DURACION_ESTIMADA","PRV_TIPO_VUELO","PRV_ESTADO") VALUES (1,'AV640',1,1,2,'08:30','09:20',50,'directo','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_PROGRAMAVUELO" ("PRV_ID","PRV_NUMERO_VUELO","PRV_ID_AEROLINEA","PRV_ID_AEROPUERTO_ORIGEN","PRV_ID_AEROPUERTO_DESTINO","PRV_HORA_SALIDA_PROGRAMADA","PRV_HORA_LLEGADA_PROGRAMADA","PRV_DURACION_ESTIMADA","PRV_TIPO_VUELO","PRV_ESTADO") VALUES (2,'5U421',2,1,3,'10:15','12:25',130,'directo','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_DIASVUELO" ("DIA_ID_DIA_VUELO","DIA_ID_PROGRAMA_VUELO","DIA_DIA_SEMANA") VALUES (1,1,1);
INSERT INTO "AEROPUERTO_AURORA"."AER_DIASVUELO" ("DIA_ID_DIA_VUELO","DIA_ID_PROGRAMA_VUELO","DIA_DIA_SEMANA") VALUES (2,1,3);
INSERT INTO "AEROPUERTO_AURORA"."AER_DIASVUELO" ("DIA_ID_DIA_VUELO","DIA_ID_PROGRAMA_VUELO","DIA_DIA_SEMANA") VALUES (3,2,2);

INSERT INTO "AEROPUERTO_AURORA"."AER_VUELO" ("VUE_ID_VUELO","VUE_ID_PROGRAMA_VUELO","VUE_ID_AVION","VUE_FECHA_VUELO","VUE_HORA_SALIDA_REAL","VUE_HORA_LLEGADA_REAL","VUE_PLAZAS_OCUPADAS","VUE_PLAZAS_VACIAS","VUE_ESTADO","VUE_RETRASO_MINUTOS") VALUES (1,1,1,DATE '2026-04-24',TIMESTAMP '2026-04-24 08:35:00',TIMESTAMP '2026-04-24 09:25:00',2,178,'PROGRAMADO',5);
INSERT INTO "AEROPUERTO_AURORA"."AER_VUELO" ("VUE_ID_VUELO","VUE_ID_PROGRAMA_VUELO","VUE_ID_AVION","VUE_FECHA_VUELO","VUE_HORA_SALIDA_REAL","VUE_HORA_LLEGADA_REAL","VUE_PLAZAS_OCUPADAS","VUE_PLAZAS_VACIAS","VUE_ESTADO","VUE_RETRASO_MINUTOS") VALUES (2,2,2,DATE '2026-04-24',TIMESTAMP '2026-04-24 10:20:00',TIMESTAMP '2026-04-24 12:35:00',1,71,'ABORDANDO',5);

INSERT INTO "AEROPUERTO_AURORA"."AER_TRIPULACION" ("TRI_ID_TRIPULACION","TRI_ID_VUELO","TRI_ID_EMPLEADO","TRI_ROL","TRI_HORAS_VUELO") VALUES (1,1,1,'piloto',1);
INSERT INTO "AEROPUERTO_AURORA"."AER_TRIPULACION" ("TRI_ID_TRIPULACION","TRI_ID_VUELO","TRI_ID_EMPLEADO","TRI_ROL","TRI_HORAS_VUELO") VALUES (2,1,2,'copiloto',1);
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIGNACION_PUERTA" ("ASP_ID_ASIGNACION","ASP_ID_VUELO","ASP_ID_PUERTA","ASP_FECHA_HORA_INICIO","ASP_FECHA_HORA_FIN","ASP_ESTADO") VALUES (1,1,1,TIMESTAMP '2026-04-24 07:30:00',TIMESTAMP '2026-04-24 09:00:00','PROGRAMADA');

INSERT INTO "AEROPUERTO_AURORA"."AER_RESERVA" ("RES_ID_RESERVA","RES_ID_VUELO","RES_ID_PASAJERO","RES_CLASE","RES_FECHA_RESERVA","RES_ESTADO","RES_EQUIPAJE_FACTURADO","RES_PESO_EQUIPAJE","RES_TARIFA_PAGADA","RES_CODIGO_RESERVA") VALUES (1,1,1,'economica',DATE '2026-04-18','CONFIRMADA',1,18.50,135.00,'RSV-0001');
INSERT INTO "AEROPUERTO_AURORA"."AER_RESERVA" ("RES_ID_RESERVA","RES_ID_VUELO","RES_ID_PASAJERO","RES_CLASE","RES_FECHA_RESERVA","RES_ESTADO","RES_EQUIPAJE_FACTURADO","RES_PESO_EQUIPAJE","RES_TARIFA_PAGADA","RES_CODIGO_RESERVA") VALUES (2,1,2,'primera',DATE '2026-04-18','CONFIRMADA',1,21.00,245.00,'RSV-0002');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIGNACION_ASIENTO" ("AAS_ID_ASIGNACION","AAS_ID_VUELO","AAS_ID_PASAJERO","AAS_ID_ASIENTO","AAS_ESTADO") VALUES (1,1,1,2,'CONFIRMADA');
INSERT INTO "AEROPUERTO_AURORA"."AER_ASIGNACION_ASIENTO" ("AAS_ID_ASIGNACION","AAS_ID_VUELO","AAS_ID_PASAJERO","AAS_ID_ASIENTO","AAS_ESTADO") VALUES (2,1,2,1,'CONFIRMADA');

INSERT INTO "AEROPUERTO_AURORA"."AER_PUNTOVENTA" ("PUV_ID_PUNTO_VENTA","PUV_CODIGO_PUNTO","PUV_NOMBRE","PUV_ID_AEROPUERTO","PUV_UBICACION","PUV_ESTADO") VALUES (1,'PV-WEB','Portal web',NULL,'Canal digital','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_VENTABOLETO" ("VEN_ID_VENTA","VEN_NUMERO_VENTA","VEN_ID_PUNTO_VENTA","VEN_ID_EMPLEADO_VENDEDOR","VEN_ID_PASAJERO","VEN_MONTO_SUBTOTAL","VEN_IMPUESTOS","VEN_DESCUENTOS","VEN_MONTO_TOTAL","VEN_ID_METODO_PAGO","VEN_CANAL_VENTA","VEN_ESTADO") VALUES (1,'VEN-2026-0001',1,NULL,1,135.00,16.20,13.50,137.70,1,'web','COMPLETADA');
INSERT INTO "AEROPUERTO_AURORA"."AER_DETALLEVENTABOLETO" ("DEV_ID_DETALLE_VENTA","DEV_ID_VENTA","DEV_ID_RESERVA","DEV_PRECIO_BASE","DEV_CARGOS_ADICIONALES") VALUES (1,1,1,135.00,0);
INSERT INTO "AEROPUERTO_AURORA"."AER_TRANSACCIONPAGO" ("TRA_ID_TRANSACCION","TRA_ID_RESERVA","TRA_ID_METODO_PAGO","TRA_MONTO_TOTAL","TRA_MONEDA","TRA_ESTADO","TRA_NUMERO_AUTORIZACION","TRA_REFERENCIA_EXTERNA","TRA_IP_CLIENTE","TRA_DETALLES_TARJETA") VALUES (1,1,1,137.70,'GTQ','APROBADA','AUTH-1001','REF-WEB-1001','192.168.1.10','Visa **** 1234');
INSERT INTO "AEROPUERTO_AURORA"."AER_USOPROMOCION" ("USO_ID_USO","USO_ID_PROMOCION","USO_ID_RESERVA","USO_MONTO_DESCUENTO") VALUES (1,1,1,13.50);

INSERT INTO "AEROPUERTO_AURORA"."AER_CHECKIN" ("CHK_ID_CHECKIN","CHK_ID_RESERVA","CHK_ID_PASAJERO","CHK_ID_VUELO","CHK_FECHA_HORA","CHK_METODO","CHK_ESTADO") VALUES (1,1,1,1,TIMESTAMP '2026-04-24 06:55:00','app','COMPLETADO');
INSERT INTO "AEROPUERTO_AURORA"."AER_TARJETA_EMBARQUE" ("TAE_ID_TARJETA","TAE_ID_CHECKIN","TAE_CODIGO_QR","TAE_GRUPO_ABORDAJE","TAE_ZONA") VALUES (1,1,'QR-AUR-RSV-0001','B','media');
INSERT INTO "AEROPUERTO_AURORA"."AER_EQUIPAJE" ("EQU_ID_EQUIPAJE","EQU_ID_PASAJERO","EQU_ID_VUELO","EQU_CODIGO_BARRAS","EQU_PESO_KG","EQU_ESTADO") VALUES (1,1,1,'BAG-GUA-0001',18.50,'REGISTRADO');
INSERT INTO "AEROPUERTO_AURORA"."AER_MOVIMIENTO_EQUIPAJE" ("MEQ_ID_MOVIMIENTO","MEQ_ID_EQUIPAJE","MEQ_UBICACION","MEQ_ESTADO","MEQ_OBSERVACION") VALUES (1,1,'Mostrador A','REGISTRADO','Recibido en mostrador');
INSERT INTO "AEROPUERTO_AURORA"."AER_CONTROL_SEGURIDAD" ("CSE_ID_CONTROL","CSE_ID_PASAJERO","CSE_ID_VUELO","CSE_ID_EMPLEADO","CSE_RESULTADO","CSE_OBSERVACION") VALUES (1,1,1,3,'APROBADO','Sin observaciones');

--------------------------------------------------------
-- MANTENIMIENTO E INCIDENTES
--------------------------------------------------------
INSERT INTO "AEROPUERTO_AURORA"."AER_HANGAR" ("HAN_ID_HANGAR","HAN_CODIGO_HANGAR","HAN_NOMBRE","HAN_ID_AEROPUERTO","HAN_CAPACIDAD_AVIONES","HAN_AREA_M2","HAN_ALTURA_MAXIMA","HAN_TIPO","HAN_ESTADO") VALUES (1,'H-AUR-01','Hangar Norte',1,3,5200,18.5,'mantenimiento ligero','DISPONIBLE');
INSERT INTO "AEROPUERTO_AURORA"."AER_CATEGORIAREPUESTO" ("CAT_ID_CATEGORIA","CAT_NOMBRE","CAT_DESCRIPCION") VALUES (1,'Motor','Componentes relacionados con motor');
INSERT INTO "AEROPUERTO_AURORA"."AER_REPUESTO" ("REP_ID_REPUESTO","REP_CODIGO_REPUESTO","REP_NOMBRE","REP_DESCRIPCION","REP_ID_CATEGORIA","REP_ID_MODELO_AVION","REP_NUMERO_PARTE_FABRICANTE","REP_STOCK_MINIMO","REP_STOCK_ACTUAL","REP_STOCK_MAXIMO","REP_PRECIO_UNITARIO","REP_UBICACION_BODEGA","REP_ESTADO") VALUES (1,'REP-MOT-001','Filtro de aceite A320','Filtro certificado',1,1,'A320-OIL-F01',2,8,20,320.00,'Bodega M1','ACTIVO');
INSERT INTO "AEROPUERTO_AURORA"."AER_PROVEEDOR" ("PRV_ID_PROVEEDOR","PRV_NOMBRE_EMPRESA","PRV_NIT","PRV_TELEFONO","PRV_EMAIL","PRV_CONTACTO_NOMBRE","PRV_ESTADO","PRV_CALIFICACION") VALUES (1,'AeroParts Centroamerica','NIT-AP-001','2424-1111','ventas@aeroparts.test','Marvin Salazar','ACTIVO',4.75);
INSERT INTO "AEROPUERTO_AURORA"."AER_ORDENCOMPRAREPUESTO" ("ORC_ID_ORDEN_COMPRA","ORC_NUMERO_ORDEN","ORC_ID_PROVEEDOR","ORC_FECHA_ORDEN","ORC_FECHA_ENTREGA_ESPERADA","ORC_MONTO_TOTAL","ORC_ESTADO","ORC_ID_EMPLEADO_SOLICITA","ORC_OBSERVACIONES") VALUES (1,'OC-2026-0001',1,DATE '2026-04-18',DATE '2026-04-30',1280.00,'PENDIENTE',4,'Reposicion de filtros');
INSERT INTO "AEROPUERTO_AURORA"."AER_DETALLEORDENCOMPRA" ("DET_ID_DETALLE","DET_ID_ORDEN_COMPRA","DET_ID_REPUESTO","DET_CANTIDAD","DET_PRECIO_UNITARIO","DET_SUBTOTAL") VALUES (1,1,1,4,320.00,1280.00);
INSERT INTO "AEROPUERTO_AURORA"."AER_MANTENIMIENTOAVION" ("MAN_ID_MANTENIMIENTO","MAN_ID_AVION","MAN_TIPO_MANTENIMIENTO","MAN_FECHA_INICIO","MAN_FECHA_FIN_ESTIMADA","MAN_DESCRIPCION_TRABAJO","MAN_ID_EMPLEADO_RESPONSABLE","MAN_COSTO_MANO_OBRA","MAN_COSTO_REPUESTOS","MAN_COSTO_TOTAL","MAN_ESTADO") VALUES (1,1,'preventivo',TIMESTAMP '2026-04-20 08:00:00',TIMESTAMP '2026-04-20 17:00:00','Revision preventiva general.',4,900,320,1220,'PROGRAMADO');
INSERT INTO "AEROPUERTO_AURORA"."AER_REPUESTOUTILIZADO" ("RUT_ID_REPUESTO_UTILIZADO","RUT_ID_MANTENIMIENTO","RUT_ID_REPUESTO","RUT_CANTIDAD") VALUES (1,1,1,1);
INSERT INTO "AEROPUERTO_AURORA"."AER_INCIDENTE" ("INC_ID_INCIDENTE","INC_TIPO","INC_DESCRIPCION","INC_SEVERIDAD","INC_ESTADO","INC_ID_VUELO","INC_ID_EMPLEADO_REPORTA") VALUES (1,'equipaje','Equipaje demorado en traslado interno.','media','ABIERTO',1,3);
INSERT INTO "AEROPUERTO_AURORA"."AER_OBJETOPERDIDO" ("OBJ_ID_OBJETO","OBJ_ID_VUELO","OBJ_ID_AEROPUERTO","OBJ_DESCRIPCION","OBJ_UBICACION_ENCONTRADO","OBJ_ESTADO","OBJ_REP_PRIMER_NOMBRE","OBJ_REP_PRIMER_APELLIDO","OBJ_CONTACTO_REPORTANTE") VALUES (1,1,1,'Mochila azul con documentos','Sala A1','REPORTADO','Luis','Perez','5600-0001');
INSERT INTO "AEROPUERTO_AURORA"."AER_AUDITORIA" ("AUD_ID_AUDITORIA","AUD_TABLA_AFECTADA","AUD_OPERACION","AUD_USUARIO","AUD_IP_ADDRESS","AUD_DATOS_ANTERIORES","AUD_DATOS_NUEVOS") VALUES (1,'AER_RESERVA','INSERT','seed_loader','127.0.0.1',NULL,'{"reserva":"RSV-0001"}');

COMMIT;
PROMPT Data de prueba cargada correctamente.