PROMPT ============================================
PROMPT MIGRACION: SNAPSHOT DE PASAJERO EN DETALLE
PROMPT ============================================
PROMPT Este script:
PROMPT 1. Agrega nombre y documento al detalle del boleto
PROMPT 2. Rellena datos historicos desde RESERVA + PASAJERO
PROMPT 3. Agrega validacion para nombre obligatorio
PROMPT ============================================

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'AER_DETALLEVENTABOLETO'
       AND COLUMN_NAME = 'DEV_NOMBRE_PASAJERO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE AER_DETALLEVENTABOLETO ADD (DEV_NOMBRE_PASAJERO VARCHAR2(200))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'AER_DETALLEVENTABOLETO'
       AND COLUMN_NAME = 'DEV_TIPO_DOCUMENTO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE AER_DETALLEVENTABOLETO ADD (DEV_TIPO_DOCUMENTO VARCHAR2(20))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'AER_DETALLEVENTABOLETO'
       AND COLUMN_NAME = 'DEV_NUMERO_DOCUMENTO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE AER_DETALLEVENTABOLETO ADD (DEV_NUMERO_DOCUMENTO VARCHAR2(50))';
    END IF;
END;
/

UPDATE AER_DETALLEVENTABOLETO d
SET (
    DEV_NOMBRE_PASAJERO,
    DEV_TIPO_DOCUMENTO,
    DEV_NUMERO_DOCUMENTO
) = (
    SELECT
        TRIM(
            p.PAS_PRIMER_NOMBRE || ' ' ||
            NVL(p.PAS_SEGUNDO_NOMBRE || ' ', '') ||
            p.PAS_PRIMER_APELLIDO || ' ' ||
            NVL(p.PAS_SEGUNDO_APELLIDO, '')
        ),
        p.PAS_TIPO_DOCUMENTO,
        p.PAS_NUMERO_DOCUMENTO
    FROM AER_RESERVA r
    INNER JOIN AER_PASAJERO p
        ON p.PAS_ID_PASAJERO = r.RES_ID_PASAJERO
    WHERE r.RES_ID_RESERVA = d.DEV_ID_RESERVA
)
WHERE NVL(TRIM(DEV_NOMBRE_PASAJERO), ' ') = ' ';

UPDATE AER_DETALLEVENTABOLETO
SET DEV_NOMBRE_PASAJERO = 'PASAJERO SIN NOMBRE'
WHERE NVL(TRIM(DEV_NOMBRE_PASAJERO), ' ') = ' ';

DECLARE
    v_count NUMBER := 0;
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AER_DETALLEVENTABOLETO MODIFY (DEV_NOMBRE_PASAJERO VARCHAR2(200) NOT NULL)';

    SELECT COUNT(*)
      INTO v_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'AER_DETALLEVENTABOLETO'
       AND CONSTRAINT_NAME = 'CHK_DETVENTA_NOMBRE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE AER_DETALLEVENTABOLETO
            ADD CONSTRAINT CHK_DETVENTA_NOMBRE
            CHECK (LENGTH(TRIM(DEV_NOMBRE_PASAJERO)) > 0) ENABLE';
    END IF;
END;
/

COMMIT;

PROMPT ============================================
PROMPT MIGRACION COMPLETADA
PROMPT ============================================
