--------------------------------------------------------
-- AEROPUERTO AURORA - RESET DE IDENTITY COLUMNS
-- Ejecutar despues del seed si insertaste IDs fijos.
-- Oracle 21c soporta START WITH LIMIT VALUE para avanzar cada
-- identity al siguiente valor seguro segun la data existente.
--------------------------------------------------------

ALTER SESSION SET CURRENT_SCHEMA = AEROPUERTO_AURORA;

BEGIN
    FOR identity_column IN (
        SELECT table_name, column_name
        FROM user_tab_identity_cols
        ORDER BY table_name
    ) LOOP
        EXECUTE IMMEDIATE
            'ALTER TABLE "' || identity_column.table_name || '" MODIFY "' ||
            identity_column.column_name ||
            '" GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)';
    END LOOP;
END;
/

COMMIT;
